spring:
  data:
    mongodb:
      database: microratingdb # Database name.
      uri: mongodb://localhost:27017/
  application:
    name: RATING-SERVICE
server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/